l_english:
  pm_government_run_general_industry: "Government Run"
  pm_privately_owned_building_subsistence: "Landlord Ownership"
  pm_skyscraper_bureaucratic_nexus: "Bureaucratic Nexus"
  pm_steam_trains: "Steam Trains"
  pm_electric_trains: "Electric Trains"
  pm_diesel_trains: "Diesel Trains"
  pm_steam_power: "Steam locomotives"
  pm_oil_power: "Unrefined fuel locomotives"
  pm_diesel_power: "Diesel locomotives"
  pm_electric_power: "Electric locomotives"
  pm_basic_rolling_stock: "Pre War Rolling Stock"
  pm_improved_rolling_stock: "Improved rolling stock"
  pm_advanced_rolling_stock: "Advanced rolling stock"
  pm_modern_rolling_stock: "Modern Rolling Stock"
  pm_conventional_track: "Standart track"
  pm_high_speed_track: "High speed track"
  pm_maglev_track: "Maglev track"
